/* Greece Life Admin — guided life-event navigator. Official-source-first, local-only. */
(()=>{
  const events=[
    {icon:'🧳',title:'Μόλις μετακόμισα στην Ελλάδα',intro:'Οργάνωσε τα βασικά βήματα χωρίς να ψάχνεις σε δεκάδες ιστοσελίδες.',steps:[['Βρες τις υπηρεσίες για πολίτες τρίτων χωρών','https://www.gov.gr/en/ipiresies/polites-kai-kathemerinoteta/polites-kai-demosio'],['Έλεγξε υπηρεσίες διεύθυνσης κατοικίας','https://www.gov.gr/'],['Έλεγξε φορολογικές υπηρεσίες / ΑΑΔΕ','https://www.aade.gr/'],['Έλεγξε υγεία και ασφάλιση','https://www.gov.gr/'],['Βρες τοπικές υπηρεσίες και ΚΕΠ','https://www.gov.gr/']]},
    {icon:'💼',title:'Ξεκινώ νέα δουλειά',intro:'Μια πρακτική λίστα εκκίνησης για εργασία, ασφάλιση και δημόσιες διαδικασίες.',steps:[['Υπηρεσίες εργασίας και ασφάλισης','https://www.gov.gr/'],['Έλεγχος ασφαλιστικής ενημέρωσης / e-ΕΦΚΑ','https://www.efka.gov.gr/'],['Φορολογικές υπηρεσίες','https://www.aade.gr/'],['Βρες αρμόδιο ΚΕΠ ή δημόσια υπηρεσία','https://www.gov.gr/']]},
    {icon:'🏠',title:'Αλλάζω σπίτι',intro:'Οργάνωσε αλλαγή διεύθυνσης, κατοικία και τις σχετικές δημόσιες υπηρεσίες.',steps:[['Υπηρεσίες διεύθυνσης και κατοικίας','https://www.gov.gr/'],['Έλεγχος φορολογικών στοιχείων / ΑΑΔΕ','https://www.aade.gr/'],['Βρες δήμο ή ΚΕΠ','https://www.gov.gr/'],['Έλεγχος ασφάλισης / υπηρεσιών υγείας','https://www.gov.gr/']]},
    {icon:'👶',title:'Νέα οικογένεια / παιδί',intro:'Ξεκίνα από τις επίσημες υπηρεσίες οικογένειας και ληξιαρχικών γεγονότων.',steps:[['Οικογένεια και ληξιαρχικές υπηρεσίες','https://www.gov.gr/'],['Πιστοποιητικά και αντίγραφα','https://www.gov.gr/'],['Υγεία και πρόνοια','https://www.gov.gr/'],['Παροχές και κοινωνική υποστήριξη','https://www.gov.gr/']]},
    {icon:'🚗',title:'Αγοράζω ή αλλάζω όχημα',intro:'Βρες τις επίσημες υπηρεσίες για άδεια οδήγησης και οχήματα.',steps:[['Μεταφορές και οχήματα','https://www.gov.gr/'],['Υπηρεσίες άδειας οδήγησης','https://www.gov.gr/'],['Φορολογικές υπηρεσίες','https://www.aade.gr/']]},
    {icon:'🏢',title:'Ξεκινώ επιχείρηση',intro:'Ένα ασφαλές σημείο εκκίνησης για επίσημες διαδικασίες επιχειρηματικής δραστηριότητας.',steps:[['Επιχειρηματική δραστηριότητα στο gov.gr','https://www.gov.gr/'],['ΑΑΔΕ — φορολογικές υπηρεσίες','https://www.aade.gr/'],['Εργασία και ασφάλιση','https://www.gov.gr/']]},
    {icon:'🌍',title:'Είμαι Έλληνας στο εξωτερικό',intro:'Βρες τις υπηρεσίες που το gov.gr συγκεντρώνει ειδικά για Έλληνες που ζουν ή βρίσκονται εκτός Ελλάδας.',steps:[['Έλληνες του εξωτερικού','https://www.gov.gr/en/'],['Προξενικές υπηρεσίες μέσω ΥΠΕΞ','https://www.mfa.gr/'],['Ψηφιακές δημόσιες υπηρεσίες','https://www.gov.gr/']]}
  ];
  const css=`.gla-events{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px auto;max-width:1280px}.gla-event{border:1px solid #dedbd2;background:#fffdf8;border-radius:18px;padding:16px;text-align:left;cursor:pointer;font:inherit;box-shadow:0 5px 18px rgba(21,37,32,.04);transition:.18s}.gla-event:hover{transform:translateY(-3px);border-color:#e36b46}.gla-event b{display:block;margin-top:9px}.gla-event small{display:block;color:#6d756f;margin-top:4px}.gla-event-modal{position:fixed;inset:0;background:rgba(7,20,17,.62);backdrop-filter:blur(6px);z-index:10000;display:grid;place-items:center;padding:16px}.gla-event-card{width:min(720px,100%);max-height:88vh;overflow:auto;background:#fffdf8;border-radius:25px;padding:25px;color:#17201d}.gla-event-card h2{margin:0 0 7px;font-size:30px}.gla-step{display:flex;gap:12px;align-items:flex-start;padding:13px 0;border-bottom:1px solid #ebe7dc}.gla-step input{margin-top:5px;width:19px;height:19px}.gla-step a{color:#176353;font-weight:850;text-decoration:none}.gla-event-close{float:right;border:0;background:#ebe7dc;border-radius:10px;padding:8px 11px;cursor:pointer;font-weight:900}@media(max-width:900px){.gla-events{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.gla-events{grid-template-columns:1fr}.gla-event-card{padding:19px;border-radius:20px}}`;
  const s=document.createElement('style');s.textContent=css;document.head.appendChild(s);
  const open=e=>{const key='gla-event-'+e.title;const done=JSON.parse(localStorage.getItem(key)||'[]');const m=document.createElement('div');m.className='gla-event-modal';m.innerHTML=`<section class="gla-event-card"><button class="gla-event-close">✕</button><h2>${e.icon} ${e.title}</h2><p style="color:#6d756f">${e.intro}</p><div>${e.steps.map((x,i)=>`<label class="gla-step"><input type="checkbox" data-i="${i}" ${done.includes(i)?'checked':''}><span><strong>${x[0]}</strong><br><a href="${x[1]}" target="_blank" rel="noopener">Άνοιγμα επίσημης πηγής →</a></span></label>`).join('')}</div><p style="font-size:11px;color:#6d756f;margin-top:18px">Οι σύνδεσμοι οδηγούν σε επίσημες πηγές. Έλεγξε πάντα τις τρέχουσες απαιτήσεις πριν ολοκληρώσεις μια διαδικασία.</p></section>`;m.onclick=x=>{if(x.target===m||x.target.classList.contains('gla-event-close'))m.remove()};m.querySelectorAll('[data-i]').forEach(c=>c.onchange=()=>{let d=JSON.parse(localStorage.getItem(key)||'[]');d=c.checked?[...new Set([...d,+c.dataset.i])]:d.filter(i=>i!==+c.dataset.i);localStorage.setItem(key,JSON.stringify(d));});document.body.appendChild(m)};
  const host=document.querySelector('.main');if(!host)return;const wrap=document.createElement('section');wrap.innerHTML='<div style="max-width:1280px;margin:25px auto 4px"><div style="font-size:11px;font-weight:950;letter-spacing:.12em;text-transform:uppercase;color:#176353">✨ Ζωή στην Ελλάδα</div><h2 style="font-size:26px;letter-spacing:-.04em;margin:6px 0 0">Ξεκίνα από αυτό που σου συμβαίνει τώρα</h2><p style="color:#6d756f;margin:4px 0">Έτοιμα σενάρια που σε οδηγούν βήμα-βήμα στις επίσημες υπηρεσίες.</p></div><div class="gla-events">${events.map((e,i)=>`<button class="gla-event" data-i="${i}"><span style="font-size:28px">${e.icon}</span><b>${e.title}</b><small>${e.steps.length} βήματα</small></button>`).join('')}</div>`;host.insertBefore(wrap,host.querySelector('.search-wrap'));wrap.querySelectorAll('.gla-event').forEach(b=>b.onclick=()=>open(events[+b.dataset.i]));
})();
